### ISSUE TITLE
Some tests are outdated/failing

### ISSUE THREAD

**Issue by j-jacobson** [j-jacobson/apple-music-python#4]
FEEF...........................F....
======================================================================
ERROR: test_activity (__main__.TestApple)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jonathan/Projects/apple-music-python/apple-music-python/tests.py", line 141, in test_activity
    results = am.activity(self.party)
  File "/Users/jonathan/Projects/apple-music-python/apple-music-python/applemusicpy/client.py", line 588, in activity
    return self._get_resource(activity_id, 'activities', storefront=storefront, l=l, include=include)
  File "/Users/jonathan/Projects/apple-music-python/apple-music-python/applemusicpy/client.py", line 208, in _get_resource
    return self._get(url, **kwargs)
  File "/Users/jonathan/Projects/apple-music-python/apple-music-python/applemusicpy/client.py", line 165, in _get
    return self._call('GET', url, kwargs)
  File "/Users/jonathan/Projects/apple-music-python/apple-music-python/applemusicpy/client.py", line 121, in _call
    r.raise_for_status()  # Check for error
  File "/Users/jonathan/Library/Python/3.9/lib/python/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.music.apple.com/v1/catalog/us/activities/976439514

======================================================================
ERROR: test_activity_relationship (__main__.TestApple)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jonathan/Projects/apple-music-python/apple-music-python/tests.py", line 145, in test_activity_relationship
    results = am.activity_relationship(self.party, 'playlists')
  File "/Users/jonathan/Projects/apple-music-python/apple-music-python/applemusicpy/client.py", line 602, in activity_relationship
    return self._get_resource_relationship(activity_id, 'activities', relationship, storefront=storefront,
  File "/Users/jonathan/Projects/apple-music-python/apple-music-python/applemusicpy/client.py", line 223, in _get_resource_relationship
    return self._get(url, **kwargs)
  File "/Users/jonathan/Projects/apple-music-python/apple-music-python/applemusicpy/client.py", line 165, in _get
    return self._call('GET', url, kwargs)
  File "/Users/jonathan/Projects/apple-music-python/apple-music-python/applemusicpy/client.py", line 121, in _call
    r.raise_for_status()  # Check for error
  File "/Users/jonathan/Library/Python/3.9/lib/python/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.music.apple.com/v1/catalog/us/activities/976439514/playlists

======================================================================
FAIL: test_activities (__main__.TestApple)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jonathan/Projects/apple-music-python/apple-music-python/tests.py", line 150, in test_activities
    self.assertTrue(len(results['data']) == 2)
AssertionError: False is not true

======================================================================
FAIL: test_album (__main__.TestApple)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jonathan/Projects/apple-music-python/apple-music-python/tests.py", line 48, in test_album
    self.assertTrue(results['data'][0]['attributes']['name'] == 'Born To Run')
AssertionError: False is not true

======================================================================
FAIL: test_station (__main__.TestApple)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jonathan/Projects/apple-music-python/apple-music-python/tests.py", line 120, in test_station
    self.assertTrue(results['data'][0]['attributes']['name'] == 'Alternative')
AssertionError: False is not true

----------------------------------------------------------------------
Ran 36 tests in 44.504s

FAILED (failures=3, errors=2)

**Comment by j-jacobson** [comment]
Seems like the values for some of the items have changed. Is there a way to get this information? Might be possible to utilize the search function to make the test not have this issue again?
i.e. Search for the <thing under test>, log the ID of the thing, use that to access it, instead of having a table of values in the test.

**Comment by j-jacobson** [comment]
Specific ones are:
Song: Born to Run
Activity: Party (and possibly Chill)
Station: Alternative
